version: 1
build:
  main: ./cmd/petri
  binary: petri
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 39000000000000stake
  mnemonic: entry garbage bike poem grunt negative easily annual miss happy license
    blur false fringe program picture inner tape dismiss eagle include quality drill
    master
- name: bob
  coins:
  - 5500000000000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
validators:
- name: alice
  bonded: 100000stake
