version: '3'

services:
  petrinode0:
    container_name: petrinode0
    image: petrilabs:petri
    ports:
    - "26656-26657:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node0 && petri start --home petri'
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  petrinode1:
    container_name: petrinode1
    image: petrilabs:petri
    ports:
    - "26659-26660:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node1 && petri start --home petri'
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  petrinode2:
    container_name: petrinode2
    image: petrilabs:petri
    ports:
    - "26661-26662:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node2 && petri start --home petri'
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  petrinode3:
    container_name: petrinode3
    image: petrilabs:petri
    ports:
    - "26663-26664:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node3 && petri start --home petri'
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
